name: Deploy Battle App

on:
  push:
    branches: [ main ]
    paths:
      - 'battle/frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: battle/frontend/package-lock.json

      - name: Install Dependencies
        run: |
          cd battle/frontend
          npm ci

      - name: Build
        run: |
          cd battle/frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: battle/frontend/dist
          branch: gh-pages
          clean: true 