name: Deploy Battle App to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Debug Info
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing contents of dist folder:"
          ls -la frontend/dist
          echo "Git status:"
          git status
          echo "Git remote:"
          git remote -v

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
          destination_dir: .  # Changed from 'battle' to root of gh-pages
          commit_message: "Deploy battle app"
          force_orphan: true  # Force clean deployment
          keep_files: false   # Don't keep any existing files 